### ISSUE TITLE
getCardData() only returns first slot.

### ISSUE THREAD

**Issue by Geird** [Zuxelus/Energy-Control#18]
Version: EnergyControl-1.12.2-0.1.8

What happened: After trying to multiple times, I can't seem to find a way to read any data beyond the first slot of an information panel. Based on the documentation I expected getCardData() to return "Reactor Status","100","10 000","8 500","0","5:30:18" but it just seems to return "Reactor Status".

Setup / example below.

![1 (1)](https://user-images.githubusercontent.com/23565524/104864521-3a23cd00-5907-11eb-9ba6-b8d55f9a2b88.png)
The program.
![1 (2)](https://user-images.githubusercontent.com/23565524/104864522-3a23cd00-5907-11eb-8c61-eb4d13cf951c.png)
Result.
![1 (3)](https://user-images.githubusercontent.com/23565524/104864523-3abc6380-5907-11eb-8898-caffb28048b8.png)
Result with title removed.
![1 (5)](https://user-images.githubusercontent.com/23565524/104864525-3b54fa00-5907-11eb-880f-44a25542c6a6.png)
Result with title and temperature removed.
![1 (6)](https://user-images.githubusercontent.com/23565524/104864527-3b54fa00-5907-11eb-9562-ec96dc1ab769.png)

Full mod list, if that's useful.

[modlist.txt](https://github.com/Zuxelus/Energy-Control/files/5827377/modlist.txt)

**Comment by Zuxelus** [comment]
Function getCardData() is correct but it returns java array instead of string. Seems that CC:Tweaked cannot handle arrays.
It works it in lua console but not in lua program.

Console
> lua
lua> x=peripheral.wrap('right')
lua> x.getCardData()
"0"
"Off"
"10 000"
"8 500"
"0"
"0:00:00"
lua>

Program
local x=peripheral.wrap('right')
print(x.getCardData())
Result
0  Off 10 000 8 500 0 0:00:00

Program2
local x=peripheral.wrap('right')
print(x.getCardData())
Result
string <- here it should be not string


I can add a parameter and return result in different formats (array, json, plain text, etc.)

**Comment by Zuxelus** [comment]
Fixed in EnergyControl-1.12.2-0.1.9.jar
